---
- name: Example3
  hosts: web-server1
  tasks:
    - name: Stop secret
      ansible.legacy.command: set -o pipefail && date +%s | sha256sum | base64 | head -c 32 ; echo
      args:
        executable: /bin/bash
      register: command_output
      changed_when: false

    - name: Print command output
      ansible.builtin.debug:
        msg: "Secret password is {{ command_output.stdout }}"

- name: Example3-2
  hosts: web-server2
  tasks:
    - name: Print password
      ansible.builtin.debug:
        msg: "Secret password is {{ command_output.stdout }}"
